#!/bin/bash

# ===== Sources ===================================================================================

script_dir=$(dirname "${BASH_SOURCE[0]}")
source "$script_dir/lib/ansi.sh"
source "$script_dir/lib/settings.sh"
source "$script_dir/lib/menu.sh"
source "$script_dir/lib/tools/reverse_proxy.sh"
source "$script_dir/lib/utils.sh"

# ===== Utils =====================================================================================

# ===== Menu Builders =============================================================================

# Display the main menu
build_menu_main() {
   menu_header="Main Menu"
   menu=(
      "${RED}Exit${RESET}" "exit 0"
      "Tools" "build_menu_tools"
      "${DIM}Edit settings${RESET}" "build_menu_settings"
   )
}

# Display the tools menu
build_menu_tools() {
   menu_header="Tools"
   menu=(
      "${RED}Back${RESET}" "build_menu_main"
      "${BLUE}RPM${INVERSE_OFF} ${DIM}(Reverse Proxy Manager)${RESET}" "build_menu_reverse_proxy"
   )
}

# Display the settings menu
# build_menu_settings now provided by settings.sh (built-in)

# build_menu_reverse_proxy now provided by tools/reverse_proxy.sh

# ===== Main ======================================================================================

settings_load_from_file ""

# Build the main menu
build_menu_main

# Run the menu
menu_start
